-- +goose Up
-- +goose StatementBegin
INSERT INTO movies (title, year, description, director) VALUES
('Citizen Kane', 1941, 'A media tycoon''s rise and fall is investigated through the memories of those who knew him in this groundbreaking masterpiece of cinematic storytelling.', 'Orson Welles'),
('The Godfather', 1972, 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son in one of the most influential films ever made.', 'Francis Ford Coppola'),
('Vertigo', 1958, 'A retired detective with a fear of heights becomes obsessed with the mysterious woman he has been hired to follow.', 'Alfred Hitchcock'),
('2001: A Space Odyssey', 1968, 'Humanity''s evolution from tool-using apes to star children, guided by mysterious black monoliths.', 'Stanley Kubrick'),
('Tokyo Story', 1953, 'An elderly couple visits their busy children in post-war Tokyo, only to feel quietly neglected.', 'Yasujirō Ozu'),
('The Rules of the Game', 1939, 'A comic and tragic portrayal of French aristocracy and their servants during a weekend hunting party on the eve of World War II.', 'Jean Renoir'),
('Seven Samurai', 1954, 'A poor village hires seven masterless samurai to defend them against bandits in 16th-century Japan.', 'Akira Kurosawa'),
('8½', 1963, 'A famous director suffering from creative block retreats into memories and fantasies.', 'Federico Fellini'),
('Singin'' in the Rain', 1952, 'A joyous celebration of Hollywood''s transition from silent films to talkies, widely considered the greatest movie musical.', 'Stanley Donen, Gene Kelly'),
('Bicycle Thieves', 1948, 'In postwar Rome, a man and his young son desperately search for a stolen bicycle needed for his job.', 'Vittorio De Sica'),
('The Godfather Part II', 1974, 'The parallel stories of a young Vito Corleone building his empire and his son Michael expanding and tightening his grip.', 'Francis Ford Coppola'),
('Casablanca', 1942, 'A cynical nightclub owner in WWII Morocco must choose between love and virtue when his ex-lover reappears.', 'Michael Curtiz'),
('Pulp Fiction', 1994, 'Interwoven stories of Los Angeles mobsters, fringe players, and small-time criminals in a nonlinear masterpiece.', 'Quentin Tarantino'),
('Lawrence of Arabia', 1962, 'The epic story of T.E. Lawrence, the British officer who united Arab tribes during World War I.', 'David Lean'),
('Sunrise: A Song of Two Humans', 1927, 'A farmer is tempted to murder his wife but rediscovers his love for her during a day in the city.', 'F.W. Murnau'),
('The Searchers', 1956, 'A Civil War veteran spends years searching for his abducted niece in a complex meditation on race and revenge.', 'John Ford'),
('Apocalypse Now', 1979, 'A U.S. Army officer is sent into Cambodia to assassinate a renegade colonel who has gone insane.', 'Francis Ford Coppola'),
('Taxi Driver', 1976, 'A mentally unstable Vietnam War veteran becomes a night-time taxi driver in decaying New York City.', 'Martin Scorsese'),
('Rashomon', 1950, 'Four contradictory accounts of a crime reveal the nature of truth and human self-deception.', 'Akira Kurosawa'),
('Sunset Boulevard', 1950, 'A faded silent-film star ensnares a struggling screenwriter in her delusional comeback fantasy.', 'Billy Wilder'),
('The 400 Blows', 1959, 'A misunderstood adolescent in Paris turns to petty crime before a heartbreaking escape attempt.', 'François Truffaut'),
('Some Like It Hot', 1959, 'Two musicians witness a mob hit and flee Chicago disguised as women in an all-female band.', 'Billy Wilder'),
('Psycho', 1960, 'A secretary embezzles money and checks into a remote motel run by a peculiar young man.', 'Alfred Hitchcock'),
('Raging Bull', 1980, 'The brutal rise and self-destructive fall of middleweight boxer Jake LaMotta.', 'Martin Scorsese'),
('La Dolce Vita', 1960, 'A jaded journalist drifts through Rome''s high society in search of love and meaning.', 'Federico Fellini'),
('City Lights', 1931, 'The Tramp falls in love with a blind flower girl and tries everything to help her regain her sight.', 'Charlie Chaplin'),
('Modern Times', 1936, 'Chaplin''s Little Tramp struggles to survive in the industrialized world.', 'Charlie Chaplin'),
('Breathless', 1960, 'A small-time French crook and his American girlfriend go on the run after he kills a policeman.', 'Jean-Luc Godard'),
('Metropolis', 1927, 'In a futuristic city sharply divided between workers and planners, a young man tries to mediate.', 'Fritz Lang'),
('The Passion of Joan of Arc', 1928, 'The trial and execution of Joan of Arc, told almost entirely in intense close-ups.', 'Carl Theodor Dreyer'),
('Andrei Rublev', 1966, 'The life of the great 15th-century Russian icon painter amid violence and spiritual crisis.', 'Andrei Tarkovsky'),
('Persona', 1966, 'A nurse and her mute actress patient begin to psychologically merge identities.', 'Ingmar Bergman'),
('Wild Strawberries', 1957, 'An elderly professor reflects on his life during a road trip to receive an award.', 'Ingmar Bergman'),
('The Seventh Seal', 1957, 'A medieval knight plays chess with Death while the plague ravages the land.', 'Ingmar Bergman'),
('L''Avventura', 1960, 'A woman disappears during a yachting trip; her lover and best friend begin a relationship while searching.', 'Michelangelo Antonioni'),
('Au Hasard Balthazar', 1966, 'The life of a donkey passed from owner to owner reflects human cruelty and grace.', 'Robert Bresson'),
('Stalker', 1979, 'A guide leads two men into the Zone, where a room supposedly grants one''s deepest desires.', 'Andrei Tarkovsky'),
('Mirror', 1975, 'A dying man recalls his childhood, marriage, and the history of 20th-century Russia in poetic fragments.', 'Andrei Tarkovsky'),
('The Night of the Hunter', 1955, 'A sinister preacher pursues two children who hold the secret to stolen money.', 'Charles Laughton'),
('Goodfellas', 1990, 'The rise and fall of mob associate Henry Hill and his friends over three decades.', 'Martin Scorsese');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM movies WHERE title IN (
  'Citizen Kane',
  'The Godfather',
  'Vertigo',
  '2001: A Space Odyssey',
  'Tokyo Story',
  'The Rules of the Game',
  'Seven Samurai',
  '8½',
  'Singin'' in the Rain',
  'Bicycle Thieves',
  'The Godfather Part II',
  'Casablanca',
  'Pulp Fiction',
  'Lawrence of Arabia',
  'Sunrise: A Song of Two Humans',
  'The Searchers',
  'Apocalypse Now',
  'Taxi Driver',
  'Rashomon',
  'Sunset Boulevard',
  'The 400 Blows',
  'Some Like It Hot',
  'Psycho',
  'Raging Bull',
  'La Dolce Vita',
  'City Lights',
  'Modern Times',
  'Breathless',
  'Metropolis',
  'The Passion of Joan of Arc',
  'Andrei Rublev',
  'Persona',
  'Wild Strawberries',
  'The Seventh Seal',
  'L''Avventura',
  'Au Hasard Balthazar',
  'Stalker',
  'Mirror',
  'The Night of the Hunter',
  'Goodfellas'
);
-- +goose StatementEnd
