{
 "title": "Movie service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Movie service total requests by outcome",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "movie_get_details_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Movie popularity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "movie_popularity_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Movie service logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"movie_service\"} |= `` | json"
    }
   ]
  }
 ]
}